module.exports = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SYNC_TIME: 'SYNC_TIME',
  NEW_VIDEO: 'NEW_VIDEO',
  GET_VIDEO_URL: 'GET_VIDEO_URL',
  SYNC_VIDEO_INFORMATION: 'SYNC_VIDEO_INFORMATION',
  GET_VIDEO_INFORMATION: 'GET_VIDEO_INFORMATION',
  JOIN_ROOM: 'JOIN_ROOM',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',
  GET_USERNAME: 'GET_USERNAME',
  SEND_USERNAME: 'SEND_USERNAME',
  GET_USERS: 'GET_USERS'
}