module.exports = {
  USER_JOINED: 'USER_JOINED',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SYNC_TIME: 'SYNC_TIME',
  NEW_VIDEO: 'NEW_VIDEO',
  GET_VIDEO_URL: 'GET_VIDEO_URL',
  SYNC_VIDEO_INFORMATION: 'SYNC_VIDEO_INFORMATION',
  GET_VIDEO_INFORMATION: 'GET_VIDEO_INFORMATION',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE: 'MESSAGE',
  GET_ROOM_DATA: 'GET_ROOM_DATA',
  GET_USERS: 'GET_USERS',
  NEW_USER_JOINED: 'NEW_USER_JOINED'
}